f1_dbt:
  target: docker
  outputs:
    docker:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: TRANSFORM_ROLE
      database: F1_DB
      warehouse: F1_WH
      schema: ANALYTICS
      threads: 4