-- Snowflake setup
-- Run this once in a Snowflake workspace to provision the warehouse, database, schemas, role and raw tables this project expects. 

CREATE WAREHOUSE IF NOT EXISTS F1_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS F1_DB;

USE DATABASE F1_DB;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

SELECT CURRENT_USER();

CREATE ROLE IF NOT EXISTS TRANSFORM_ROLE;
GRANT ROLE TRANSFORM_ROLE TO USER <>; -- Removed username for security. 
GRANT ALL ON WAREHOUSE F1_WH TO ROLE TRANSFORM_ROLE;
GRANT ALL ON DATABASE F1_DB TO ROLE TRANSFORM_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE F1_DB TO ROLE TRANSFORM_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE F1_DB TO ROLE TRANSFORM_ROLE;

USE ROLE ACCOUNTADMIN;
USE DATABASE F1_DB;

CREATE SCHEMA IF NOT EXISTS F1_DB.RAW;
CREATE SCHEMA IF NOT EXISTS F1_DB.ANALYTICS;

CREATE OR REPLACE TABLE F1_DB.RAW.RACES (
  season INT, round INT, race_name STRING, circuit_id STRING,
  race_date DATE, race_time STRING
);

CREATE OR REPLACE TABLE F1_DB.RAW.RESULTS (
  season INT, round INT, driver_id STRING, constructor_id STRING,
  grid INT, position INT, points FLOAT, status STRING, fastest_lap_rank INT
);

CREATE OR REPLACE TABLE F1_DB.RAW.QUALIFYING (
  season INT, round INT, driver_id STRING, constructor_id STRING,
  position INT, q1 STRING, q2 STRING, q3 STRING
);

CREATE OR REPLACE TABLE F1_DB.RAW.PIT_STOPS (
  season INT, round INT, driver_id STRING, stop INT,
  lap INT, pit_time STRING, duration_ms INT
);

CREATE OR REPLACE TABLE F1_DB.RAW.DRIVERS (
  driver_id STRING, given_name STRING, family_name STRING,
  nationality STRING, date_of_birth DATE
);

CREATE OR REPLACE TABLE F1_DB.RAW.CONSTRUCTORS (
  constructor_id STRING, name STRING, nationality STRING
);

CREATE OR REPLACE TABLE F1_DB.RAW.LAPS (
  season INT, round INT, driver_id STRING, lap_number INT,
  lap_time_sec FLOAT, position INT, compound STRING, tyre_life INT
);

CREATE OR REPLACE TABLE F1_DB.RAW.STINTS (
  season INT, round INT, driver_id STRING, stint INT,
  compound STRING, lap_start INT, lap_end INT
);

SHOW TABLES IN SCHEMA F1_DB.RAW;

SELECT COUNT(*) FROM F1_DB.RAW.LAPS;
SELECT COUNT(*) FROM F1_DB.RAW.STINTS;
SELECT * FROM F1_DB.RAW.STINTS LIMIT 10;

SELECT CURRENT_ORGANIZATION_NAME(), CURRENT_ACCOUNT_NAME();

SELECT COUNT(*) FROM F1_DB.RAW.RACES;
SELECT COUNT(*) FROM F1_DB.RAW.LAPS;

SELECT COUNT(*) FROM F1_DB.RAW.DRIVERS;
SELECT COUNT(*) FROM F1_DB.RAW.CONSTRUCTORS;

SELECT * FROM F1_DB.ANALYTICS.MART_QUALIFYING_VS_RACE_PACE ORDER BY positions_gained DESC LIMIT 10;
SELECT * FROM F1_DB.ANALYTICS.MART_CHAMPIONSHIP_PROGRESSION ORDER BY cumulative_points DESC LIMIT 10;

SELECT * FROM F1_DB.ANALYTICS.MART_CHAMPIONSHIP_PROGRESSION ORDER BY cumulative_points DESC LIMIT 10;